version: '3'

# Вариант сборки для разработки
services:
  frontend: 
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev

    command: npm run start
    # Есть баг - интерактивная консоль реакта, запущенного в докер-контейнере, 
    # не работает из коробки. Чтобы пофиксить это, добавим следующие 2 настройки
    stdin_open: true
    tty: true

    volumes:
      # Создаем инлайн-симлинк (без имени) для папки проекта ./frontend/src 
      # на машине разработчика, ссылающийся на путь в контейнере /usr/src/app/src
      - ./frontend/src:/usr/src/app/src

  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src

  auth:
    command: npm run dev
    volumes:
      - ./auth/src:/usr/src/app/src

  nginx:    
    volumes:
    # Конфиг для разработки (слева) будет помещен в контейнер по пути справа
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
  


# Команда на старт компоуза (подъем контейнеров) с предварительным билдом 
# (если были изменения в коде), причем сначала читается первый указанный 
# с опицией -f файл, затем второй файл, который переписывает совпадающие 
# ключи новыми значениями и потом начинается старт

# docker compose -f docker-compose.yml -f docker-compose.development.yml up --build

