version: '3'

# Вариант сборки для продакшена
services:
  api:
    build: ./api
    container_name: 02_proj-api
    command: npm run start
    restart: unless-stopped
    # Слева - порт хоста (наша локальная машина). Справа - порт контейнера.
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=http://02-proj.com
      - MONGO_URL=mongodb://api_db:27017/api
    # Свойство depends_on означает, что сначала мы хотим запустить БД api_db, 
    # и только после этого стартануть сервис-контейнер api 
    depends_on:
      - api_db
  auth:
      build: ./auth
      container_name: 02_proj-auth
      command: npm run start
      restart: unless-stopped
      # Слева - порт хоста (наша локальная машина). Справа - порт контейнера.
      ports:
        - "3001:3001"
      environment:
        - PORT=3001 # Порт контейнера (значение справа от :)
        - HOST=http://02-proj.com
        - MONGO_URL=mongodb://auth_db:27017/auth
      depends_on:
        - auth_db

  api_db:
    image: mongo:latest
    container_name: 02_proj-api_db
    volumes:
      # Симлинк mongodb_api, ссылающийся на путь в контейнере
      - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: 02_proj-auth_db
    volumes:
      # Симлинк mongodb_auth, ссылающийся на путь в контейнере
      - mongodb_auth:/data/db

# Эти вольюмы мы можем шарить между нашими сервисами (контейнерами)
volumes:
  mongodb_api:
  mongodb_auth:


