version: '3'

# Вариант сборки для разработки
services:
  api:
    command: npm run dev
    volumes:
      # Создаем инлайн-симлинк (без имени) для папки проекта ./api/src 
      # на машине разработчика, ссылающийся на путь в контейнере /usr/src/app/src
      - ./api/src:/usr/src/app/src



# Команда на старт компоуза (подъем контейнеров) с предварительным билдом 
# (если были изменения в коде), причем сначала читается первый указанный 
# с опицией -f файл, затем второй файл, который переписывает совпадающие 
# ключи новыми значениями и потом начинается старт

# docker compose -f docker-compose.yml -f docker-compose.development.yml up --build

